// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA18-SBnVi6jG-bx32bCgv66AqObGqpqF4',
    appId: '1:877690983328:web:379222f9439e6c4fd74ac5',
    messagingSenderId: '877690983328',
    projectId: 'reminder-bd0cd',
    authDomain: 'reminder-bd0cd.firebaseapp.com',
    storageBucket: 'reminder-bd0cd.firebasestorage.app',
    measurementId: 'G-CMJ0GK75Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO2ni5GtmEcwdRQmQicMnQRJym2rW5OKk',
    appId: '1:877690983328:android:0a2ec40584e7c02ed74ac5',
    messagingSenderId: '877690983328',
    projectId: 'reminder-bd0cd',
    storageBucket: 'reminder-bd0cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfYVtRNRpMdzow2XpuX2rvoaYsM0i_8Bw',
    appId: '1:877690983328:ios:0aae1c08008a5ec1d74ac5',
    messagingSenderId: '877690983328',
    projectId: 'reminder-bd0cd',
    storageBucket: 'reminder-bd0cd.firebasestorage.app',
    iosBundleId: 'com.example.medicalReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfYVtRNRpMdzow2XpuX2rvoaYsM0i_8Bw',
    appId: '1:877690983328:ios:0aae1c08008a5ec1d74ac5',
    messagingSenderId: '877690983328',
    projectId: 'reminder-bd0cd',
    storageBucket: 'reminder-bd0cd.firebasestorage.app',
    iosBundleId: 'com.example.medicalReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA18-SBnVi6jG-bx32bCgv66AqObGqpqF4',
    appId: '1:877690983328:web:226887fe87b129aad74ac5',
    messagingSenderId: '877690983328',
    projectId: 'reminder-bd0cd',
    authDomain: 'reminder-bd0cd.firebaseapp.com',
    storageBucket: 'reminder-bd0cd.firebasestorage.app',
    measurementId: 'G-K590F5DB2G',
  );
}
